### ISSUE TITLE
Can you please describe how you create the compressed exe?

### ISSUE THREAD

**Issue by malicious-user** [3gstudent/msbuild-inline-task#1]
The question is regarding the" executes mimikatz.xml" template.
I first base64 the executable I want to load, as follows.

"$fileName = "executable"
$fileContent = get-content $fileName
$fileContentBytes = [System.Text.Encoding]::UTF8.GetBytes($fileContent)
$fileContentEncoded = [System.Convert]::ToBase64String($fileContentBytes)
$fileContentEncoded | set-content ($fileName + ".b64")"

Then, I understand that I should gzip compress the base64 string above. (Am I correct?)

Finally, I copy paste the gzip compressed string but I always get " error MSB4018: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.\r"

Can you please describe how you create the compressed exe?

**Comment by 3gstudent** [comment]
@malicious-user 

To read the binary file,you should use this:

`[System.IO.File]::ReadAllBytes('$fileName')`

not `get-content $fileName`

**Comment by eliranc22** [comment]
Hi,
can you please explain how I should use the gzip compressed after i get the base64 string?

**Comment by 3gstudent** [comment]
https://github.com/3gstudent/Homework-of-C-Sharp/blob/master/GzipandBase64.cs

**Comment by clod81** [comment]
Hi,
I tried to use the above `GzipandBase64.cs` against the latest `mimikatz.exe` release.
I obtain the `base64.txt` file, replace the variable `KatzCompressed` content of the `executes mimikatz.xml` with base64.txt content:
```
public static string KatzCompressed = @"H4sIAAA...............";
```

When I run it, I get (mima.xml is the executes mimikatz.xml file):
```
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe mima.xml
Microsoft (R) Build Engine version 4.8.4084.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/27/2020 5:09:13 PM.
Preferred Load Address = 0000
Allocated Space For 0000 at 0000
Project "C:\Users\clod\tools\mima.xml" on node 1 (default targets).
C:\Users\clod\tools\mima.xml(8,5): error MSB4018: The "ClassExample" task failed unexpectedly.\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018: System.ArgumentNullException: Value cannot be null.\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018: Parameter name: destination\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at System.Runtime.InteropServices.Marshal.CopyToNative(Object source, Int32 startIndex, IntPtr destination, Int32 length)\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at ClassExample.Execute() in c:\Users\clod\AppData\Local\Temp\jdepagrt\jdepagrt.0.cs:line 127\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
Done Building Project "C:\Users\clod\tools\mima.xml" (default targets) -- FAILED.


Build FAILED.

"C:\Users\clod\tools\mima.xml" (default target) (1) ->
(Hello target) ->
  C:\Users\clod\tools\mima.xml(8,5): error MSB4018: The "ClassExample" task failed unexpectedly.\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018: System.ArgumentNullException: Value cannot be null.\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018: Parameter name: destination\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at System.Runtime.InteropServices.Marshal.CopyToNative(Object source, Int32 startIndex, IntPtr destination, Int32 length)\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at ClassExample.Execute() in c:\Users\clod\AppData\Local\Temp\jdepagrt\jdepagrt.0.cs:line 127\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r
C:\Users\clod\tools\mima.xml(8,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.92
```
